CREATE DATABASE IF NOT EXISTS dalessio_nadia_DWES04;

USE dalessio_nadia_DWES04;

-- Estructura tabla Pokemon
CREATE TABLE IF NOT EXISTS Pokemon (
  idPokemon	INT NOT NULL PRIMARY KEY,
  NamePkm	VARCHAR(512) NOT NULL UNIQUE,
  TypePkm	VARCHAR(512) NOT NULL,
  Generation	INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Volcado de datos para la tabla Pokemon
INSERT INTO Pokemon (idPokemon, NamePkm, TypePkm, Generation) VALUES
	('1', 'Bulbasaur', 'Planta,Veneno', '1'),
	('2', 'Ivysaur', 'Planta,Veneno', '1'),
	('3', 'Venusaur', 'Planta,Veneno', '1'),
	('4', 'Charmander', 'Fuego', '1'),
	('5', 'Charmeleon', 'Fuego', '1'),
	('6', 'Charizard', 'Fuego,Volador', '1'),
	('7', 'Squirtle', 'Agua', '1'),
	('8', 'Wartortle', 'Agua', '1'),
	('9', 'Blastoise', 'Agua', '1'),
	('10', 'Caterpie', 'Bicho', '1'),
	('11', 'Metapod', 'Bicho', '1'),
	('12', 'Butterfree', 'Bicho,Volador', '1'),
	('13', 'Weedle', 'Bicho,Veneno', '1'),
	('14', 'Kakuna', 'Bicho,Veneno', '1'),
	('15', 'Beedrill', 'Bicho,Veneno', '1'),
	('16', 'Pidgey', 'Normal,Volador', '1'),
	('17', 'Pidgeotto', 'Normal,Volador', '1'),
	('18', 'Pidgeot', 'Normal,Volador', '1'),
	('19', 'Rattata', 'Normal', '1'),
	('20', 'Rattata Alola', 'Normal,Siniestro', '7'),
	('21', 'Raticate', 'Normal', '1'),
	('22', 'Raticate Alola', 'Normal,Siniestro', '7'),
	('23', 'Spearow', 'Normal,Volador', '1'),
	('24', 'Fearow', 'Normal,Volador', '1'),
	('25', 'Ekans', 'Veneno', '1'),
	('26', 'Arbok', 'Veneno', '1'),
	('27', 'Pikachu', 'Electrico', '1'),
	('28', 'Raichu', 'Electrico', '1'),
	('29', 'Raichu Alola', 'Electrico,Psiquico', '7'),
	('30', 'Sandshrew', 'Tierra', '1'),
	('31', 'Sandshrew Alola', 'Hielo,Acero', '7'),
	('32', 'Sandslash', 'Tierra', '1'),
	('33', 'Sandslash Alola', 'Hielo,Acero', '7'),
	('34', 'NidoranF', 'Veneno', '1'),
	('35', 'Nidorina', 'Veneno', '1'),
	('36', 'Nidoqueen', 'Veneno,Tierra', '1'),
	('37', 'NidoranM', 'Veneno', '1'),
	('38', 'Nidorino', 'Veneno', '1'),
	('39', 'Nidoking', 'Veneno,Tierra', '1'),
	('40', 'CleHada', 'Hada', '1'),
	('41', 'Clefable', 'Hada', '1'),
	('42', 'Vulpix', 'Fuego', '1'),
	('43', 'Vulpix Alola', 'Hielo', '7'),
	('44', 'Ninetales', 'Fuego', '1'),
	('45', 'Ninetales Alola', 'Hielo', '7'),
	('46', 'Jigglypuff', 'Normal,Hada', '1'),
	('47', 'Wigglytuff', 'Normal,Hada', '1'),
	('48', 'Zubat', 'Veneno,Volador', '1'),
	('49', 'Golbat', 'Veneno,Volador', '1'),
	('50', 'Oddish', 'Planta,Veneno', '1'),
	('51', 'Gloom', 'Planta,Veneno', '1'),
	('52', 'Vileplume', 'Planta,Veneno', '1'),
	('53', 'Paras', 'Bicho,Planta', '1'),
	('54', 'Parasect', 'Bicho,Planta', '1'),
	('55', 'Venonat', 'Bicho,Veneno', '1'),
	('56', 'Venomoth', 'Bicho,Veneno', '1'),
	('57', 'Diglett', 'Tierra', '1'),
	('58', 'Diglett Alola', 'Tierra,Acero', '7'),
	('59', 'Dugtrio', 'Tierra', '1'),
	('60', 'Dugtrio Alola', 'Tierra,Acero', '7'),
	('61', 'Meowth', 'Normal', '1'),
	('62', 'Meowth Alola', 'Siniestro', '7'),
	('63', 'Persian', 'Normal', '1'),
	('64', 'Persian Alola', 'Siniestro', '7'),
	('65', 'Psyduck', 'Agua', '1'),
	('66', 'Golduck', 'Agua', '1'),
	('67', 'Mankey', 'Lucha', '1'),
	('68', 'Primeape', 'Lucha', '1'),
	('69', 'Growlithe', 'Fuego', '1'),
	('70', 'Growlithe Hisui', 'Fuego,Roca', '8'),
	('71', 'Arcanine', 'Fuego', '1'),
	('72', 'Arcanine Hisui', 'Fuego,Roca', '8'),
	('73', 'Poliwag', 'Agua', '1'),
	('74', 'Poliwhirl', 'Agua', '1'),
	('75', 'Poliwrath', 'Agua,Lucha', '1'),
	('76', 'Abra', 'Psiquico', '1'),
	('77', 'Kadabra', 'Psiquico', '1'),
	('78', 'Alakazam', 'Psiquico', '1'),
	('79', 'Machop', 'Lucha', '1'),
	('80', 'Machoke', 'Lucha', '1'),
	('81', 'Machamp', 'Lucha', '1'),
	('82', 'Bellsprout', 'Planta,Veneno', '1'),
	('83', 'Weepinbell', 'Planta,Veneno', '1'),
	('84', 'Victreebel', 'Planta,Veneno', '1'),
	('85', 'Tentacool', 'Agua,Veneno', '1'),
	('86', 'Tentacruel', 'Agua,Veneno', '1'),
	('87', 'Geodude', 'Roca,Tierra', '1'),
	('88', 'Geodude Alola', 'Roca,Electrico', '7'),
	('89', 'Graveler', 'Roca,Tierra', '1'),
	('90', 'Graveler Alola', 'Roca,Electrico', '7'),
	('91', 'Golem', 'Roca,Tierra', '1'),
	('92', 'Golem Alola', 'Roca,Electrico', '7'),
	('93', 'Ponyta', 'Fuego', '1'),
	('94', 'Ponyta Galar', 'Psiquico', '8'),
	('95', 'Rapidash', 'Fuego', '1'),
	('96', 'Rapidash Galar', 'Psiquico,Hada', '8'),
	('97', 'Slowpoke', 'Agua,Psiquico', '1'),
	('98', 'Slowpoke Galar', 'Psiquico', '8'),
	('99', 'Slowbro', 'Agua,Psiquico', '1'),
	('100', 'Slowbro Galar', 'Veneno,Psiquico', '8'),
	('101', 'Magnemite', 'Electrico,Acero', '1'),
	('102', 'Magneton', 'Electrico,Acero', '1'),
	('103', 'Farfetch\'d', 'Normal,Volador', '1'),
	('104', 'Farfetch\'d Galar', 'Lucha', '8'),
	('105', 'Doduo', 'Normal,Volador', '1'),
	('106', 'Dodrio', 'Normal,Volador', '1'),
	('107', 'Seel', 'Agua', '1'),
	('108', 'Dewgong', 'Agua,Hielo', '1'),
	('109', 'Grimer', 'Veneno', '1'),
	('110', 'Grimer Alola', 'Veneno,Siniestro', '7'),
	('111', 'Muk', 'Veneno', '1'),
	('112', 'Muk Alola', 'Veneno,Siniestro', '7'),
	('113', 'Shellder', 'Agua', '1'),
	('114', 'Cloyster', 'Agua,Hielo', '1'),
	('115', 'Gastly', 'Fantasma,Veneno', '1'),
	('116', 'Haunter', 'Fantasma,Veneno', '1'),
	('117', 'Gengar', 'Fantasma,Veneno', '1'),
	('118', 'Onix', 'Roca,Tierra', '1'),
	('119', 'Drowzee', 'Psiquico', '1'),
	('120', 'Hypno', 'Psiquico', '1'),
	('121', 'Krabby', 'Agua', '1'),
	('122', 'Kingler', 'Agua', '1'),
	('123', 'Voltorb', 'Electrico', '1'),
	('124', 'Voltorb Hisui', 'Electrico,Planta', '8'),
	('125', 'Electrode', 'Electrico', '1'),
	('126', 'Electrode Hisui', 'Electrico,Planta', '8'),
	('127', 'Exeggcute', 'Planta,Psiquico', '1'),
	('128', 'Exeggutor', 'Planta,Psiquico', '1'),
	('129', 'Exeggutor Alola', 'Planta,Dragon', '7'),
	('130', 'Cubone', 'Tierra', '1'),
	('131', 'Marowak', 'Tierra', '1'),
	('132', 'Marowak Alola', 'Fuego,Fantasma', '7'),
	('133', 'Hitmonlee', 'Lucha', '1'),
	('134', 'Hitmonchan', 'Lucha', '1'),
	('135', 'Lickitung', 'Normal', '1'),
	('136', 'Koffing', 'Veneno', '1'),
	('137', 'Weezing', 'Veneno', '1'),
	('138', 'Weezing Galar', 'Veneno,Hada', '8'),
	('139', 'Rhyhorn', 'Tierra,Roca', '1'),
	('140', 'Rhydon', 'Tierra,Roca', '1'),
	('141', 'Chansey', 'Normal', '1'),
	('142', 'Tangela', 'Planta', '1'),
	('143', 'Kangaskhan', 'Normal', '1'),
	('144', 'Horsea', 'Agua', '1'),
	('145', 'Seadra', 'Agua', '1'),
	('146', 'Goldeen', 'Agua', '1'),
	('147', 'Seaking', 'Agua', '1'),
	('148', 'Staryu', 'Agua', '1'),
	('149', 'Starmie', 'Agua,Psiquico', '1'),
	('150', 'Mr. Mime', 'Psiquico,Hada', '1'),
	('151', 'Mr. Mime Galar', 'Psiquico,Hielo', '8'),
	('152', 'Scyther', 'Bicho,Volador', '1'),
	('153', 'Jynx', 'Hielo,Psiquico', '1'),
	('154', 'Electabuzz', 'Electrico', '1'),
	('155', 'Magmar', 'Fuego', '1'),
	('156', 'Pinsir', 'Bicho', '1'),
	('157', 'Tauros', 'Normal', '1'),
	('158', 'Tauros Paldea', 'Lucha', '9'),
	('159', 'Tauros Blaze Paldea', 'Lucha,Fuego', '9'),
	('160', 'Tauros Aqua Paldea', 'Lucha,Agua', '9'),
	('161', 'Magikarp', 'Agua', '1'),
	('162', 'Gyarados', 'Agua,Volador', '1'),
	('163', 'Lapras', 'Agua,Hielo', '1'),
	('164', 'Ditto', 'Normal', '1'),
	('165', 'Eevee', 'Normal', '1'),
	('166', 'Vaporeon', 'Agua', '1'),
	('167', 'Jolteon', 'Electrico', '1'),
	('168', 'Flareon', 'Fuego', '1'),
	('169', 'Porygon', 'Normal', '1'),
	('170', 'Omanyte', 'Roca,Agua', '1'),
	('171', 'Omastar', 'Roca,Agua', '1'),
	('172', 'Kabuto', 'Roca,Agua', '1'),
	('173', 'Kabutops', 'Roca,Agua', '1'),
	('174', 'Aerodactyl', 'Roca,Volador', '1'),
	('175', 'Snorlax', 'Normal', '1'),
	('176', 'Articuno', 'Hielo,Volador', '1'),
	('177', 'Articuno Galar', 'Psiquico,Volador', '8'),
	('178', 'Zapdos', 'Electrico,Volador', '1'),
	('179', 'Zapdos Galar', 'Lucha,Volador', '8'),
	('180', 'Moltres', 'Fuego,Volador', '1'),
	('181', 'Moltres Galar', 'Siniestro,Volador', '8'),
	('182', 'Dratini', 'Dragon', '1'),
	('183', 'Dragonair', 'Dragon', '1'),
	('184', 'Dragonite', 'Dragon,Volador', '1'),
	('185', 'Mewtwo', 'Psiquico', '1'),
	('186', 'Mew', 'Psiquico', '1'),
	('187', 'Chikorita', 'Planta', '2'),
	('188', 'Bayleef', 'Planta', '2'),
	('189', 'Meganium', 'Planta', '2'),
	('190', 'Cyndaquil', 'Fuego', '2'),
	('191', 'Quilava', 'Fuego', '2'),
	('192', 'Typhlosion', 'Fuego', '2'),
	('193', 'Typhlosion Hisui', 'Fuego,Fantasma', '8'),
	('194', 'Totodile', 'Agua', '2'),
	('195', 'Croconaw', 'Agua', '2'),
	('196', 'Feraligatr', 'Agua', '2'),
	('197', 'Sentret', 'Normal', '2'),
	('198', 'Furret', 'Normal', '2'),
	('199', 'Hoothoot', 'Normal,Volador', '2'),
	('200', 'Noctowl', 'Normal,Volador', '2'),
	('201', 'Ledyba', 'Bicho,Volador', '2'),
	('202', 'Ledian', 'Bicho,Volador', '2'),
	('203', 'Spinarak', 'Bicho,Veneno', '2'),
	('204', 'Ariados', 'Bicho,Veneno', '2'),
	('205', 'Crobat', 'Veneno,Volador', '2'),
	('206', 'Chinchou', 'Agua,Electrico', '2'),
	('207', 'Lanturn', 'Agua,Electrico', '2'),
	('208', 'Pichu', 'Electrico', '2'),
	('209', 'Cleffa', 'Hada', '2'),
	('210', 'Igglybuff', 'Normal,Hada', '2'),
	('211', 'Togepi', 'Hada', '2'),
	('212', 'Togetic', 'Hada,Volador', '2'),
	('213', 'Natu', 'Psiquico,Volador', '2'),
	('214', 'Xatu', 'Psiquico,Volador', '2'),
	('215', 'Mareep', 'Electrico', '2'),
	('216', 'Flaaffy', 'Electrico', '2'),
	('217', 'Ampharos', 'Electrico', '2'),
	('218', 'Bellossom', 'Planta', '2'),
	('219', 'Marill', 'Agua,Hada', '2'),
	('220', 'Azumarill', 'Agua,Hada', '2'),
	('221', 'Sudowoodo', 'Roca', '2'),
	('222', 'Politoed', 'Agua', '2'),
	('223', 'Hoppip', 'Planta,Volador', '2'),
	('224', 'Skiploom', 'Planta,Volador', '2'),
	('225', 'Jumpluff', 'Planta,Volador', '2'),
	('226', 'Aipom', 'Normal', '2'),
	('227', 'Sunkern', 'Planta', '2'),
	('228', 'Sunflora', 'Planta', '2'),
	('229', 'Yanma', 'Bicho,Volador', '2'),
	('230', 'Wooper', 'Agua,Tierra', '2'),
	('231', 'Wooper Paldea', 'Veneno,Tierra', '9'),
	('232', 'Quagsire', 'Agua,Tierra', '2'),
	('233', 'Espeon', 'Psiquico', '2'),
	('234', 'Umbreon', 'Siniestro', '2'),
	('235', 'Murkrow', 'Siniestro,Volador', '2'),
	('236', 'Slowking', 'Agua,Psiquico', '2'),
	('237', 'Misdreavus', 'Fantasma', '2'),
	('238', 'Unown', 'Psiquico', '2'),
	('239', 'Wobbuffet', 'Psiquico', '2'),
	('240', 'Girafarig', 'Normal,Psiquico', '2'),
	('241', 'Pineco', 'Bicho', '2'),
	('242', 'Forretress', 'Bicho,Acero', '2'),
	('243', 'Dunsparce', 'Normal', '2'),
	('244', 'Gligar', 'Tierra,Volador', '2'),
	('245', 'Aceroix', 'Acero,Tierra', '2'),
	('246', 'Snubbull', 'Hada', '2'),
	('247', 'Granbull', 'Hada', '2'),
	('248', 'Qwilfish', 'Agua,Veneno', '2'),
	('249', 'Scizor', 'Bicho,Acero', '2'),
	('250', 'Shuckle', 'Bicho,Roca', '2'),
	('251', 'Heracross', 'Bicho,Lucha', '2'),
	('252', 'Sneasel', 'Siniestro,Hielo', '2'),
	('253', 'Teddiursa', 'Normal', '2'),
	('254', 'Ursaring', 'Normal', '2'),
	('255', 'Slugma', 'Fuego', '2'),
	('256', 'Magcargo', 'Fuego,Roca', '2'),
	('257', 'Swinub', 'Hielo,Tierra', '2'),
	('258', 'Piloswine', 'Hielo,Tierra', '2'),
	('259', 'Corsola', 'Agua,Roca', '2'),
	('260', 'Remoraid', 'Agua', '2'),
	('261', 'Octillery', 'Agua', '2'),
	('262', 'Delibird', 'Hielo,Volador', '2'),
	('263', 'Mantine', 'Agua,Volador', '2'),
	('264', 'Skarmory', 'Acero,Volador', '2'),
	('265', 'Houndour', 'Siniestro,Fuego', '2'),
	('266', 'Houndoom', 'Siniestro,Fuego', '2'),
	('267', 'Kingdra', 'Agua,Dragon', '2'),
	('268', 'Phanpy', 'Tierra', '2'),
	('269', 'Donphan', 'Tierra', '2'),
	('270', 'Porygon2', 'Normal', '2'),
	('271', 'Stantler', 'Normal', '2'),
	('272', 'Smeargle', 'Normal', '2'),
	('273', 'Tyrogue', 'Lucha', '2'),
	('274', 'Hitmontop', 'Lucha', '2'),
	('275', 'Smoochum', 'Hielo,Psiquico', '2'),
	('276', 'Elekid', 'Electrico', '2'),
	('277', 'Magby', 'Fuego', '2'),
	('278', 'Miltank', 'Normal', '2'),
	('279', 'Blissey', 'Normal', '2'),
	('280', 'Raikou', 'Electrico', '2'),
	('281', 'Entei', 'Fuego', '2'),
	('282', 'Suicune', 'Agua', '2'),
	('283', 'Larvitar', 'Roca,Tierra', '2'),
	('284', 'Pupitar', 'Roca,Tierra', '2'),
	('285', 'Tyranitar', 'Roca,Siniestro', '2'),
	('286', 'Lugia', 'Psiquico,Volador', '2'),
	('287', 'Ho-oh', 'Fuego,Volador', '2'),
	('288', 'Celebi', 'Psiquico,Planta', '2'),
	('289', 'Treecko', 'Planta', '3'),
	('290', 'Grovyle', 'Planta', '3'),
	('291', 'Sceptile', 'Planta', '3'),
	('292', 'Torchic', 'Fuego', '3'),
	('293', 'Combusken', 'Fuego,Lucha', '3'),
	('294', 'Blaziken', 'Fuego,Lucha', '3'),
	('295', 'Mudkip', 'Agua', '3'),
	('296', 'Marshtomp', 'Agua,Tierra', '3'),
	('297', 'Swampert', 'Agua,Tierra', '3'),
	('298', 'Poochyena', 'Siniestro', '3'),
	('299', 'Mightyena', 'Siniestro', '3'),
	('300', 'Zigzagoon', 'Normal', '3'),
	('301', 'Zigzagoon Galar', 'Normal,Siniestro', '8'),
	('302', 'Linoone', 'Normal', '3'),
	('303', 'Linoone Galar', 'Normal,Siniestro', '8'),
	('304', 'Wurmple', 'Bicho', '3'),
	('305', 'Silcoon', 'Bicho', '3'),
	('306', 'Beautifly', 'Bicho,Volador', '3'),
	('307', 'Cascoon', 'Bicho', '3'),
	('308', 'Dustox', 'Bicho,Veneno', '3'),
	('309', 'Lotad', 'Agua,Planta', '3'),
	('310', 'Lombre', 'Agua,Planta', '3'),
	('311', 'Ludicolo', 'Agua,Planta', '3'),
	('312', 'Seedot', 'Planta', '3'),
	('313', 'Nuzleaf', 'Planta,Siniestro', '3'),
	('314', 'Shiftry', 'Planta,Siniestro', '3'),
	('315', 'Taillow', 'Normal,Volador', '3'),
	('316', 'Swellow', 'Normal,Volador', '3'),
	('317', 'Wingull', 'Agua,Volador', '3'),
	('318', 'Pelipper', 'Agua,Volador', '3'),
	('319', 'Ralts', 'Psiquico,Hada', '3'),
	('320', 'Kirlia', 'Psiquico,Hada', '3'),
	('321', 'Gardevoir', 'Psiquico,Hada', '3'),
	('322', 'Surskit', 'Bicho,Agua', '3'),
	('323', 'Masquerain', 'Bicho,Volador', '3'),
	('324', 'Shroomish', 'Planta', '3'),
	('325', 'Breloom', 'Planta,Lucha', '3'),
	('326', 'Slakoth', 'Normal', '3'),
	('327', 'Vigoroth', 'Normal', '3'),
	('328', 'Slaking', 'Normal', '3'),
	('329', 'Nincada', 'Bicho,Tierra', '3'),
	('330', 'Ninjask', 'Bicho,Volador', '3'),
	('331', 'Shedinja', 'Bicho,Fantasma', '3'),
	('332', 'Whismur', 'Normal', '3'),
	('333', 'Loudred', 'Normal', '3'),
	('334', 'Exploud', 'Normal', '3'),
	('335', 'Makuhita', 'Lucha', '3'),
	('336', 'Hariyama', 'Lucha', '3'),
	('337', 'Azurill', 'Normal,Hada', '3'),
	('338', 'Nosepass', 'Roca', '3'),
	('339', 'Skitty', 'Normal', '3'),
	('340', 'Delcatty', 'Normal', '3'),
	('341', 'Sableye', 'Siniestro,Fantasma', '3'),
	('342', 'Mawile', 'Acero,Hada', '3'),
	('343', 'Aron', 'Acero,Roca', '3'),
	('344', 'Lairon', 'Acero,Roca', '3'),
	('345', 'Aggron', 'Acero,Roca', '3'),
	('346', 'Meditite', 'Lucha,Psiquico', '3'),
	('347', 'Medicham', 'Lucha,Psiquico', '3'),
	('348', 'Electrike', 'Electrico', '3'),
	('349', 'Manectric', 'Electrico', '3'),
	('350', 'Plusle', 'Electrico', '3'),
	('351', 'Minun', 'Electrico', '3'),
	('352', 'Volbeat', 'Bicho', '3'),
	('353', 'Illumise', 'Bicho', '3'),
	('354', 'Roselia', 'Planta,Veneno', '3'),
	('355', 'Gulpin', 'Veneno', '3'),
	('356', 'Swalot', 'Veneno', '3'),
	('357', 'Carvanha', 'Agua,Siniestro', '3'),
	('358', 'Sharpedo', 'Agua,Siniestro', '3'),
	('359', 'Wailmer', 'Agua', '3'),
	('360', 'Wailord', 'Agua', '3'),
	('361', 'Numel', 'Fuego,Tierra', '3'),
	('362', 'Camerupt', 'Fuego,Tierra', '3'),
	('363', 'Torkoal', 'Fuego', '3'),
	('364', 'Spoink', 'Psiquico', '3'),
	('365', 'Grumpig', 'Psiquico', '3'),
	('366', 'Spinda', 'Normal', '3'),
	('367', 'Trapinch', 'Tierra', '3'),
	('368', 'Vibrava', 'Tierra,Dragon', '3'),
	('369', 'Flygon', 'Tierra,Dragon', '3'),
	('370', 'Cacnea', 'Planta', '3'),
	('371', 'Cacturne', 'Planta,Siniestro', '3'),
	('372', 'Swablu', 'Normal,Volador', '3'),
	('373', 'Altaria', 'Dragon,Volador', '3'),
	('374', 'Zangoose', 'Normal', '3'),
	('375', 'Seviper', 'Veneno', '3'),
	('376', 'Lunatone', 'Roca,Psiquico', '3'),
	('377', 'SolRoca', 'Roca,Psiquico', '3'),
	('378', 'Barboach', 'Agua,Tierra', '3'),
	('379', 'Whiscash', 'Agua,Tierra', '3'),
	('380', 'Corphish', 'Agua', '3'),
	('381', 'Crawdaunt', 'Agua,Siniestro', '3'),
	('382', 'Baltoy', 'Tierra,Psiquico', '3'),
	('383', 'Claydol', 'Tierra,Psiquico', '3'),
	('384', 'Lileep', 'Roca,Planta', '3'),
	('385', 'Cradily', 'Roca,Planta', '3'),
	('386', 'Anorith', 'Roca,Bicho', '3'),
	('387', 'Armaldo', 'Roca,Bicho', '3'),
	('388', 'Feebas', 'Agua', '3'),
	('389', 'Milotic', 'Agua', '3'),
	('390', 'Castform', 'Normal', '3'),
	('391', 'Castform Sunny', 'Fuego', '3'),
	('392', 'Castform Rainy', 'Agua', '3'),
	('393', 'Castform Snowy', 'Hielo', '3'),
	('394', 'Kecleon', 'Normal', '3'),
	('395', 'Shuppet', 'Fantasma', '3'),
	('396', 'Banette', 'Fantasma', '3'),
	('397', 'Duskull', 'Fantasma', '3'),
	('398', 'Dusclops', 'Fantasma', '3'),
	('399', 'Tropius', 'Planta,Volador', '3'),
	('400', 'Chimecho', 'Psiquico', '3'),
	('401', 'Absol', 'Siniestro', '3'),
	('402', 'Wynaut', 'Psiquico', '3'),
	('403', 'Snorunt', 'Hielo', '3'),
	('404', 'Glalie', 'Hielo', '3'),
	('405', 'Spheal', 'Hielo,Agua', '3'),
	('406', 'Sealeo', 'Hielo,Agua', '3'),
	('407', 'Walrein', 'Hielo,Agua', '3'),
	('408', 'Clamperl', 'Agua', '3'),
	('409', 'Huntail', 'Agua', '3'),
	('410', 'Gorebyss', 'Agua', '3'),
	('411', 'Relicanth', 'Agua,Roca', '3'),
	('412', 'Luvdisc', 'Agua', '3'),
	('413', 'Bagon', 'Dragon', '3'),
	('414', 'Shelgon', 'Dragon', '3'),
	('415', 'Salamence', 'Dragon,Volador', '3'),
	('416', 'Beldum', 'Acero,Psiquico', '3'),
	('417', 'Metang', 'Acero,Psiquico', '3'),
	('418', 'Metagross', 'Acero,Psiquico', '3'),
	('419', 'RegiRoca', 'Roca', '3'),
	('420', 'RegHielo', 'Hielo', '3'),
	('421', 'RegiAcero', 'Acero', '3'),
	('422', 'Latias', 'Dragon,Psiquico', '3'),
	('423', 'Latios', 'Dragon,Psiquico', '3'),
	('424', 'Kyogre', 'Agua', '3'),
	('425', 'Groudon', 'Tierra', '3'),
	('426', 'Rayquaza', 'Dragon,Volador', '3'),
	('427', 'Jirachi', 'Acero,Psiquico', '3'),
	('428', 'Deoxys', 'Psiquico', '3'),
	('429', 'Turtwig', 'Planta', '4'),
	('430', 'Grotle', 'Planta', '4'),
	('431', 'Torterra', 'Planta,Tierra', '4'),
	('432', 'Chimchar', 'Fuego', '4'),
	('433', 'Monferno', 'Fuego,Lucha', '4'),
	('434', 'Infernape', 'Fuego,Lucha', '4'),
	('435', 'Piplup', 'Agua', '4'),
	('436', 'Prinplup', 'Agua', '4'),
	('437', 'Empoleon', 'Agua,Acero', '4'),
	('438', 'Starly', 'Normal,Volador', '4'),
	('439', 'Staravia', 'Normal,Volador', '4'),
	('440', 'Staraptor', 'Normal,Volador', '4'),
	('441', 'Bidoof', 'Normal', '4'),
	('442', 'Bibarel', 'Normal,Agua', '4'),
	('443', 'Kricketot', 'Bicho', '4'),
	('444', 'Kricketune', 'Bicho', '4'),
	('445', 'Shinx', 'Electrico', '4'),
	('446', 'Luxio', 'Electrico', '4'),
	('447', 'Luxray', 'Electrico', '4'),
	('448', 'Budew', 'Planta,Veneno', '4'),
	('449', 'Roserade', 'Planta,Veneno', '4'),
	('450', 'Cranidos', 'Roca', '4'),
	('451', 'Rampardos', 'Roca', '4'),
	('452', 'Shieldon', 'Roca,Acero', '4'),
	('453', 'Bastiodon', 'Roca,Acero', '4'),
	('454', 'Burmy', 'Bicho', '4'),
	('455', 'Wormadam Plant Cloak', 'Bicho,Planta', '4'),
	('456', 'Wormadam Sandy Cloak', 'Bicho,Tierra', '4'),
	('457', 'Wormadam Trash Cloak', 'Bicho,Acero', '4'),
	('458', 'Mothim', 'Bicho,Volador', '4'),
	('459', 'Combee', 'Bicho,Volador', '4'),
	('460', 'Vespiquen', 'Bicho,Volador', '4'),
	('461', 'Pachirisu', 'Electrico', '4'),
	('462', 'Buizel', 'Agua', '4'),
	('463', 'Floatzel', 'Agua', '4'),
	('464', 'Cherubi', 'Planta', '4'),
	('465', 'Cherrim', 'Planta', '4'),
	('466', 'Shellos', 'Agua', '4'),
	('467', 'Gastrodon', 'Agua,Tierra', '4'),
	('468', 'Ambipom', 'Normal', '4'),
	('469', 'Drifloon', 'Fantasma,Volador', '4'),
	('470', 'Drifblim', 'Fantasma,Volador', '4'),
	('471', 'Buneary', 'Normal', '4'),
	('472', 'Lopunny', 'Normal', '4'),
	('473', 'Mismagius', 'Fantasma', '4'),
	('474', 'Honchkrow', 'Siniestro,Volador', '4'),
	('475', 'Glameow', 'Normal', '4'),
	('476', 'Purugly', 'Normal', '4'),
	('477', 'Chingling', 'Psiquico', '4'),
	('478', 'Stunky', 'Veneno,Siniestro', '4'),
	('479', 'Skuntank', 'Veneno,Siniestro', '4'),
	('480', 'Bronzor', 'Acero,Psiquico', '4'),
	('481', 'Bronzong', 'Acero,Psiquico', '4'),
	('482', 'Bonsly', 'Roca', '4'),
	('483', 'Mime Jr.', 'Psiquico,Hada', '4'),
	('484', 'Happiny', 'Normal', '4'),
	('485', 'Chatot', 'Normal,Volador', '4'),
	('486', 'Spiritomb', 'Fantasma,Siniestro', '4'),
	('487', 'Gible', 'Dragon,Tierra', '4'),
	('488', 'Gabite', 'Dragon,Tierra', '4'),
	('489', 'Garchomp', 'Dragon,Tierra', '4'),
	('490', 'Munchlax', 'Normal', '4'),
	('491', 'Riolu', 'Lucha', '4'),
	('492', 'Lucario', 'Lucha,Acero', '4'),
	('493', 'Hippopotas', 'Tierra', '4'),
	('494', 'Hippowdon', 'Tierra', '4'),
	('495', 'Skorupi', 'Veneno,Bicho', '4'),
	('496', 'Drapion', 'Veneno,Siniestro', '4'),
	('497', 'Croagunk', 'Veneno,Lucha', '4'),
	('498', 'Toxicroak', 'Veneno,Lucha', '4'),
	('499', 'Carnivine', 'Planta', '4'),
	('500', 'Finneon', 'Agua', '4'),
	('501', 'Lumineon', 'Agua', '4'),
	('502', 'Mantyke', 'Agua,Volador', '4'),
	('503', 'Snover', 'Planta,Hielo', '4'),
	('504', 'Abomasnow', 'Planta,Hielo', '4'),
	('505', 'Weavile', 'Siniestro,Hielo', '4'),
	('506', 'Magnezone', 'Electrico,Acero', '4'),
	('507', 'Lickilicky', 'Normal', '4'),
	('508', 'Rhyperior', 'Tierra,Roca', '4'),
	('509', 'Tangrowth', 'Planta', '4'),
	('510', 'Electivire', 'Electrico', '4'),
	('511', 'Magmortar', 'Fuego', '4'),
	('512', 'Togekiss', 'Hada,Volador', '4'),
	('513', 'Yanmega', 'Bicho,Volador', '4'),
	('514', 'Leafeon', 'Planta', '4'),
	('515', 'Glaceon', 'Hielo', '4'),
	('516', 'Gliscor', 'Tierra,Volador', '4'),
	('517', 'Mamoswine', 'Hielo,Tierra', '4'),
	('518', 'Porygon-Z', 'Normal', '4'),
	('519', 'Gallade', 'Psiquico,Lucha', '4'),
	('520', 'Probopass', 'Roca,Acero', '4'),
	('521', 'Dusknoir', 'Fantasma', '4'),
	('522', 'Froslass', 'Hielo,Fantasma', '4'),
	('523', 'Rotom', 'Electrico,Fantasma', '4'),
	('524', 'Rotom Heat', 'Electrico,Fuego', '4'),
	('525', 'Rotom Wash', 'Electrico,Agua', '4'),
	('526', 'Rotom Frost', 'Electrico,Hielo', '4'),
	('527', 'Rotom Fan', 'Electrico,Volador', '4'),
	('528', 'Rotom Mow', 'Electrico,Planta', '4'),
	('529', 'Uxie', 'Psiquico', '4'),
	('530', 'Mesprit', 'Psiquico', '4'),
	('531', 'Azelf', 'Psiquico', '4'),
	('532', 'Dialga', 'Acero,Dragon', '4'),
	('533', 'Palkia', 'Agua,Dragon', '4'),
	('534', 'Heatran', 'Fuego,Acero', '4'),
	('535', 'Regigigas', 'Normal', '4'),
	('536', 'Giratina', 'Fantasma,Dragon', '4'),
	('537', 'Cresselia', 'Psiquico', '4'),
	('538', 'Phione', 'Agua', '4'),
	('539', 'Manaphy', 'Agua', '4'),
	('540', 'Siniestrorai', 'Siniestro', '4'),
	('541', 'Shaymin Land', 'Planta', '4'),
	('542', 'Shaymin Sky', 'Planta,Volador', '4'),
	('543', 'Arceus', 'Normal', '4'),
	('544', 'Victini', 'Psiquico,Fuego', '5'),
	('545', 'Snivy', 'Planta', '5'),
	('546', 'Servine', 'Planta', '5'),
	('547', 'Serperior', 'Planta', '5'),
	('548', 'Tepig', 'Fuego', '5'),
	('549', 'Pignite', 'Fuego,Lucha', '5'),
	('550', 'Emboar', 'Fuego,Lucha', '5'),
	('551', 'Oshawott', 'Agua', '5'),
	('552', 'Dewott', 'Agua', '5'),
	('553', 'Samurott', 'Agua', '5'),
	('554', 'Samurott Hisui', 'Agua,Siniestro', '8'),
	('555', 'Patrat', 'Normal', '5'),
	('556', 'Watchog', 'Normal', '5'),
	('557', 'Lillipup', 'Normal', '5'),
	('558', 'Herdier', 'Normal', '5'),
	('559', 'Stoutland', 'Normal', '5'),
	('560', 'Purrloin', 'Siniestro', '5'),
	('561', 'Liepard', 'Siniestro', '5'),
	('562', 'Pansage', 'Planta', '5'),
	('563', 'Simisage', 'Planta', '5'),
	('564', 'Pansear', 'Fuego', '5'),
	('565', 'Simisear', 'Fuego', '5'),
	('566', 'Panpour', 'Agua', '5'),
	('567', 'Simipour', 'Agua', '5'),
	('568', 'Munna', 'Psiquico', '5'),
	('569', 'Musharna', 'Psiquico', '5'),
	('570', 'Pidove', 'Normal,Volador', '5'),
	('571', 'Tranquill', 'Normal,Volador', '5'),
	('572', 'Unfezant', 'Normal,Volador', '5'),
	('573', 'Blitzle', 'Electrico', '5'),
	('574', 'Zebstrika', 'Electrico', '5'),
	('575', 'Roggenrola', 'Roca', '5'),
	('576', 'Boldore', 'Roca', '5'),
	('577', 'Gigalith', 'Roca', '5'),
	('578', 'Woobat', 'Psiquico,Volador', '5'),
	('579', 'Swoobat', 'Psiquico,Volador', '5'),
	('580', 'Drilbur', 'Tierra', '5'),
	('581', 'Excadrill', 'Tierra,Acero', '5'),
	('582', 'Audino', 'Normal', '5'),
	('583', 'Timburr', 'Lucha', '5'),
	('584', 'Gurdurr', 'Lucha', '5'),
	('585', 'Conkeldurr', 'Lucha', '5'),
	('586', 'Tympole', 'Agua', '5'),
	('587', 'Palpitoad', 'Agua,Tierra', '5'),
	('588', 'Seismitoad', 'Agua,Tierra', '5'),
	('589', 'Throh', 'Lucha', '5'),
	('590', 'Sawk', 'Lucha', '5'),
	('591', 'Sewaddle', 'Bicho,Planta', '5'),
	('592', 'Swadloon', 'Bicho,Planta', '5'),
	('593', 'Leavanny', 'Bicho,Planta', '5'),
	('594', 'Venipede', 'Bicho,Veneno', '5'),
	('595', 'Whirlipede', 'Bicho,Veneno', '5'),
	('596', 'Scolipede', 'Bicho,Veneno', '5'),
	('597', 'Cottonee', 'Planta,Hada', '5'),
	('598', 'Whimsicott', 'Planta,Hada', '5'),
	('599', 'Petilil', 'Planta', '5'),
	('600', 'Lilligant', 'Planta', '5'),
	('601', 'Lilligant Hisui', 'Planta,Lucha', '8'),
	('602', 'Basculin', 'Agua', '5'),
	('603', 'Sandile', 'Tierra,Siniestro', '5'),
	('604', 'Krokorok', 'Tierra,Siniestro', '5'),
	('605', 'Krookodile', 'Tierra,Siniestro', '5'),
	('606', 'Darumaka', 'Fuego', '5'),
	('607', 'Darumaka Galar', 'Hielo', '8'),
	('608', 'Darmanitan', 'Fuego', '5'),
	('609', 'Darmanitan Zen', 'Fuego,Psiquico', '5'),
	('610', 'Darmanitan Galar', 'Hielo', '8'),
	('611', 'Darmanitan Zen Galar', 'Fuego,Hielo', '8'),
	('612', 'Maractus', 'Planta', '5'),
	('613', 'Dwebble', 'Bicho,Roca', '5'),
	('614', 'Crustle', 'Bicho,Roca', '5'),
	('615', 'Scraggy', 'Siniestro,Lucha', '5'),
	('616', 'Scrafty', 'Siniestro,Lucha', '5'),
	('617', 'Sigilyph', 'Psiquico,Volador', '5'),
	('618', 'Yamask', 'Fantasma', '5'),
	('619', 'Yamask Galar', 'Fantasma,Tierra', '8'),
	('620', 'Cofagrigus', 'Fantasma', '5'),
	('621', 'Tirtouga', 'Agua,Roca', '5'),
	('622', 'Carracosta', 'Agua,Roca', '5'),
	('623', 'Archen', 'Roca,Volador', '5'),
	('624', 'Archeops', 'Roca,Volador', '5'),
	('625', 'Trubbish', 'Veneno', '5'),
	('626', 'Garbodor', 'Veneno', '5'),
	('627', 'Zorua', 'Siniestro', '5'),
	('628', 'Zorua Hisui', 'Normal,Fantasma', '8'),
	('629', 'Zoroark', 'Siniestro', '5'),
	('630', 'Zoroark Hisui', 'Normal,Fantasma', '8'),
	('631', 'Minccino', 'Normal', '5'),
	('632', 'Cinccino', 'Normal', '5'),
	('633', 'Gothita', 'Psiquico', '5'),
	('634', 'Gothorita', 'Psiquico', '5'),
	('635', 'Gothitelle', 'Psiquico', '5'),
	('636', 'Solosis', 'Psiquico', '5'),
	('637', 'Duosion', 'Psiquico', '5'),
	('638', 'Reuniclus', 'Psiquico', '5'),
	('639', 'Ducklett', 'Agua,Volador', '5'),
	('640', 'Swanna', 'Agua,Volador', '5'),
	('641', 'Vanillite', 'Hielo', '5'),
	('642', 'Vanillish', 'Hielo', '5'),
	('643', 'Vanilluxe', 'Hielo', '5'),
	('644', 'Deerling', 'Normal,Planta', '5'),
	('645', 'Sawsbuck', 'Normal,Planta', '5'),
	('646', 'Emolga', 'Electrico,Volador', '5'),
	('647', 'Karrablast', 'Bicho', '5'),
	('648', 'Escavalier', 'Bicho,Acero', '5'),
	('649', 'Foongus', 'Planta,Veneno', '5'),
	('650', 'Amoonguss', 'Planta,Veneno', '5'),
	('651', 'Frillish', 'Agua,Fantasma', '5'),
	('652', 'JellHielont', 'Agua,Fantasma', '5'),
	('653', 'Alomomola', 'Agua', '5'),
	('654', 'Joltik', 'Bicho,Electrico', '5'),
	('655', 'Galvantula', 'Bicho,Electrico', '5'),
	('656', 'Ferroseed', 'Planta,Acero', '5'),
	('657', 'Ferrothorn', 'Planta,Acero', '5'),
	('658', 'Klink', 'Acero', '5'),
	('659', 'Klang', 'Acero', '5'),
	('660', 'Klinklang', 'Acero', '5'),
	('661', 'Tynamo', 'Electrico', '5'),
	('662', 'Eelektrik', 'Electrico', '5'),
	('663', 'Eelektross', 'Electrico', '5'),
	('664', 'Elgyem', 'Psiquico', '5'),
	('665', 'Beheeyem', 'Psiquico', '5'),
	('666', 'Litwick', 'Fantasma,Fuego', '5'),
	('667', 'Lampent', 'Fantasma,Fuego', '5'),
	('668', 'Chandelure', 'Fantasma,Fuego', '5'),
	('669', 'Axew', 'Dragon', '5'),
	('670', 'Fraxure', 'Dragon', '5'),
	('671', 'Haxorus', 'Dragon', '5'),
	('672', 'Cubchoo', 'Hielo', '5'),
	('673', 'Beartic', 'Hielo', '5'),
	('674', 'Cryogonal', 'Hielo', '5'),
	('675', 'Shelmet', 'Bicho', '5'),
	('676', 'Accelgor', 'Bicho', '5'),
	('677', 'Stunfisk', 'Tierra,Electrico', '5'),
	('678', 'Stunfisk Galar', 'Tierra,Acero', '8'),
	('679', 'Mienfoo', 'Lucha', '5'),
	('680', 'Mienshao', 'Lucha', '5'),
	('681', 'Druddigon', 'Dragon', '5'),
	('682', 'Golett', 'Tierra,Fantasma', '5'),
	('683', 'Golurk', 'Tierra,Fantasma', '5'),
	('684', 'Pawniard', 'Siniestro,Acero', '5'),
	('685', 'Bisharp', 'Siniestro,Acero', '5'),
	('686', 'Bouffalant', 'Normal', '5'),
	('687', 'Rufflet', 'Normal,Volador', '5'),
	('688', 'Braviary', 'Normal,Volador', '5'),
	('689', 'Braviary Hisui', 'Psiquico,Volador', '8'),
	('690', 'Vullaby', 'Siniestro,Volador', '5'),
	('691', 'Mandibuzz', 'Siniestro,Volador', '5'),
	('692', 'Heatmor', 'Fuego', '5'),
	('693', 'Durant', 'Bicho,Acero', '5'),
	('694', 'Deino', 'Siniestro,Dragon', '5'),
	('695', 'Zweilous', 'Siniestro,Dragon', '5'),
	('696', 'Hydreigon', 'Siniestro,Dragon', '5'),
	('697', 'Larvesta', 'Bicho,Fuego', '5'),
	('698', 'Volcarona', 'Bicho,Fuego', '5'),
	('699', 'Cobalion', 'Acero,Lucha', '5'),
	('700', 'Terrakion', 'Roca,Lucha', '5'),
	('701', 'Virizion', 'Planta,Lucha', '5'),
	('702', 'Tornadus', 'Volador', '5'),
	('703', 'Thundurus', 'Electrico,Volador', '5'),
	('704', 'Reshiram', 'Dragon,Fuego', '5'),
	('705', 'Zekrom', 'Dragon,Electrico', '5'),
	('706', 'Landorus', 'Tierra,Volador', '5'),
	('707', 'Kyurem', 'Dragon,Hielo', '5'),
	('708', 'Keldeo', 'Agua,Lucha', '5'),
	('709', 'Meloetta Aria', 'Normal,Psiquico', '5'),
	('710', 'Meloetta Pirouette', 'Normal,Lucha', '5'),
	('711', 'Genesect', 'Bicho,Acero', '5'),
	('712', 'Chespin', 'Planta', '6'),
	('713', 'Quilladin', 'Planta', '6'),
	('714', 'Chesnaught', 'Planta,Lucha', '6'),
	('715', 'Fennekin', 'Fuego', '6'),
	('716', 'Braixen', 'Fuego', '6'),
	('717', 'Delphox', 'Fuego,Psiquico', '6'),
	('718', 'Froakie', 'Agua', '6'),
	('719', 'Frogadier', 'Agua', '6'),
	('720', 'Greninja', 'Agua,Siniestro', '6'),
	('721', 'Bunnelby', 'Normal', '6'),
	('722', 'Diggersby', 'Normal,Tierra', '6'),
	('723', 'Fletchling', 'Normal,Volador', '6'),
	('724', 'Fletchinder', 'Fuego,Volador', '6'),
	('725', 'Talonflame', 'Fuego,Volador', '6'),
	('726', 'ScatterBicho', 'Bicho', '6'),
	('727', 'Spewpa', 'Bicho', '6'),
	('728', 'Vivillon', 'Bicho,Volador', '6'),
	('729', 'Litleo', 'Fuego,Normal', '6'),
	('730', 'Pyroar', 'Fuego,Normal', '6'),
	('731', 'Flabebe', 'Hada', '6'),
	('732', 'Floette', 'Hada', '6'),
	('733', 'Florges', 'Hada', '6'),
	('734', 'Skiddo', 'Planta', '6'),
	('735', 'Gogoat', 'Planta', '6'),
	('736', 'Pancham', 'Lucha', '6'),
	('737', 'Pangoro', 'Lucha,Siniestro', '6'),
	('738', 'Furfrou', 'Normal', '6'),
	('739', 'Espurr', 'Psiquico', '6'),
	('740', 'MeowsticMale', 'Psiquico', '6'),
	('741', 'MeowsticFemale', 'Psiquico', '6'),
	('742', 'Honedge', 'Acero,Fantasma', '6'),
	('743', 'Doublade', 'Acero,Fantasma', '6'),
	('744', 'Aegislash', 'Acero,Fantasma', '6'),
	('745', 'Spritzee', 'Hada', '6'),
	('746', 'Aromatisse', 'Hada', '6'),
	('747', 'Swirlix', 'Hada', '6'),
	('748', 'Slurpuff', 'Hada', '6'),
	('749', 'Inkay', 'Siniestro,Psiquico', '6'),
	('750', 'Malamar', 'Siniestro,Psiquico', '6'),
	('751', 'Binacle', 'Roca,Agua', '6'),
	('752', 'Barbaracle', 'Roca,Agua', '6'),
	('753', 'Skrelp', 'Veneno,Agua', '6'),
	('754', 'Dragalge', 'Veneno,Dragon', '6'),
	('755', 'Clauncher', 'Agua', '6'),
	('756', 'Clawitzer', 'Agua', '6'),
	('757', 'Helioptile', 'Electrico,Normal', '6'),
	('758', 'Heliolisk', 'Electrico,Normal', '6'),
	('759', 'Tyrunt', 'Roca,Dragon', '6'),
	('760', 'Tyrantrum', 'Roca,Dragon', '6'),
	('761', 'Amaura', 'Roca,Hielo', '6'),
	('762', 'Aurorus', 'Roca,Hielo', '6'),
	('763', 'Sylveon', 'Hada', '6'),
	('764', 'Hawlucha', 'Lucha,Volador', '6'),
	('765', 'Dedenne', 'Electrico,Hada', '6'),
	('766', 'Carbink', 'Roca,Hada', '6'),
	('767', 'Goomy', 'Dragon', '6'),
	('768', 'Sliggoo', 'Dragon', '6'),
	('769', 'Sliggoo Hisui', 'Dragon,Acero', '8'),
	('770', 'Goodra', 'Dragon', '6'),
	('771', 'Goodra Hisui', 'Dragon,Acero', '8'),
	('772', 'Klefki', 'Acero,Hada', '6'),
	('773', 'Phantump', 'Fantasma,Planta', '6'),
	('774', 'Trevenant', 'Fantasma,Planta', '6'),
	('775', 'Pumpkaboo', 'Fantasma,Planta', '6'),
	('776', 'Gourgeist', 'Fantasma,Planta', '6'),
	('777', 'Bergmite', 'Hielo', '6'),
	('778', 'Avalugg', 'Hielo', '6'),
	('779', 'Avalugg Hisui', 'Hielo,Roca', '8'),
	('780', 'Noibat', 'Volador,Dragon', '6'),
	('781', 'Noivern', 'Volador,Dragon', '6'),
	('782', 'Xerneas', 'Hada', '6'),
	('783', 'Yveltal', 'Siniestro,Volador', '6'),
	('784', 'Zygarde', 'Dragon,Tierra', '6'),
	('785', 'Diancie', 'Roca,Hada', '6'),
	('786', 'Hoopa', 'Psiquico,Fantasma', '6'),
	('787', 'Hoopa Unbound', 'Psiquico,Siniestro', '6'),
	('788', 'Volcanion', 'Fuego,Agua', '6'),
	('789', 'Rowlet', 'Planta,Volador', '7'),
	('790', 'Dartrix', 'Planta,Volador', '7'),
	('791', 'Decidueye', 'Planta,Fantasma', '7'),
	('792', 'Litten', 'Fuego', '7'),
	('793', 'Torracat', 'Fuego', '7'),
	('794', 'Incineroar', 'Fuego,Siniestro', '7'),
	('795', 'Popplio', 'Agua', '7'),
	('796', 'Brionne', 'Agua', '7'),
	('797', 'Primarina', 'Agua,Hada', '7'),
	('798', 'Pikipek', 'Normal,Volador', '7'),
	('799', 'Trumbeak', 'Normal,Volador', '7'),
	('800', 'Toucannon', 'Normal,Volador', '7'),
	('801', 'Yungooos', 'Normal', '7'),
	('802', 'Gumshoos', 'Normal', '7'),
	('803', 'Grubbin', 'Bicho', '7'),
	('804', 'CharjaBicho', 'Bicho,Electrico', '7'),
	('805', 'Vikavolt', 'Bicho,Electrico', '7'),
	('806', 'Crabrawler', 'Lucha', '7'),
	('807', 'Crabominable', 'Lucha,Hielo', '7'),
	('808', 'Oricorio Baile', 'Fuego,Volador', '7'),
	('809', 'Oricorio Pom-Pom', 'Electrico,Volador', '7'),
	('810', 'Oricorio Pau', 'Psiquico,Volador', '7'),
	('811', 'Oricorio Sensu', 'Fantasma,Volador', '7'),
	('812', 'Cutiefly', 'Bicho,Hada', '7'),
	('813', 'Ribombee', 'Bicho,Hada', '7'),
	('814', 'Rocaruff', 'Roca', '7'),
	('815', 'Lyncaroc', 'Roca', '7'),
	('816', 'Wishiwashi', 'Agua', '7'),
	('817', 'Mareanie', 'Veneno,Agua', '7'),
	('818', 'Toxapex', 'Veneno,Agua', '7'),
	('819', 'Mudbray', 'Tierra', '7'),
	('820', 'Mudsdale', 'Tierra', '7'),
	('821', 'Dewpider', 'Agua,Bicho', '7'),
	('822', 'Araquanid', 'Agua,Bicho', '7'),
	('823', 'Formantis', 'Planta', '7'),
	('824', 'Lurantis', 'Planta', '7'),
	('825', 'Morelull', 'Planta,Hada', '7'),
	('826', 'Shiinotic', 'Planta,Hada', '7'),
	('827', 'Salandit', 'Veneno,Fuego', '7'),
	('828', 'Salazzle', 'Veneno,Fuego', '7'),
	('829', 'Stufful', 'Normal,Lucha', '7'),
	('830', 'Bewear', 'Normal,Lucha', '7'),
	('831', 'Bounsweet', 'Planta', '7'),
	('832', 'Steenee', 'Planta', '7'),
	('833', 'Tsareena', 'Planta', '7'),
	('834', 'Comfey', 'Hada', '7'),
	('835', 'Oranguru', 'Normal,Psiquico', '7'),
	('836', 'Passimian', 'Lucha', '7'),
	('837', 'Wimpod', 'Bicho,Agua', '7'),
	('838', 'Golisopod', 'Bicho,Agua', '7'),
	('839', 'Sandygast', 'Fantasma,Tierra', '7'),
	('840', 'Palossand', 'Fantasma,Tierra', '7'),
	('841', 'Pyukumuku', 'Agua', '7'),
	('842', 'Type Null', 'Normal', '7'),
	('843', 'Sylvally', 'Normal', '7'),
	('844', 'Minior', 'Roca,Volador', '7'),
	('845', 'Komala', 'Normal', '7'),
	('846', 'Togedemaru', 'Electrico,Acero', '7'),
	('847', 'Mimikyu', 'Fantasma,Hada', '7'),
	('848', 'Bruxish', 'Agua,Psiquico', '7'),
	('849', 'Drampa', 'Normal,Dragon', '7'),
	('850', 'Dhelmise', 'Fantasma,Planta', '7'),
	('851', 'Jangmo-o', 'Dragon', '7'),
	('852', 'Hakamo-o', 'Dragon,Lucha', '7'),
	('853', 'Kommo-o', 'Dragon,Lucha', '7'),
	('854', 'Tapu Koko', 'Electrico,Hada', '7'),
	('855', 'Tapu Lele', 'Psiquico,Hada', '7'),
	('856', 'Tapu Bulu', 'Planta,Hada', '7'),
	('857', 'Tapu Fini', 'Agua,Hada', '7'),
	('858', 'Cosmog', 'Psiquico', '7'),
	('859', 'Cosmoem', 'Psiquico', '7'),
	('860', 'Solgaleo', 'Psiquico,Acero', '7'),
	('861', 'Lunala', 'Psiquico,Fantasma', '7'),
	('862', 'Nihilego', 'Roca,Veneno', '7'),
	('863', 'Buzzwole', 'Bicho,Lucha', '7'),
	('864', 'Pheromosa', 'Bicho,Lucha', '7'),
	('865', 'Xurkitree', 'Electrico', '7'),
	('866', 'CeleAceroa', 'Acero,Volador', '7'),
	('867', 'Kartana', 'Planta,Acero', '7'),
	('868', 'Guzzlord', 'Siniestro,Dragon', '7'),
	('869', 'Necrozma', 'Psiquico', '7'),
	('870', 'Necrozma Dusk Mane', 'Psiquico,Acero', '7'),
	('871', 'Necrozma Dawn Wings', 'Psiquico,Fantasma', '7'),
	('872', 'Magearna', 'Acero,Hada', '7'),
	('873', 'Marshadow', 'Lucha,Fantasma', '7'),
	('874', 'Poipole', 'Veneno', '7'),
	('875', 'Nagandel', 'Veneno,Dragon', '7'),
	('876', 'Stakataka', 'Roca,Acero', '7'),
	('877', 'Blacephalon', 'Fuego,Fantasma', '7'),
	('878', 'Zeraora', 'Electrico', '7'),
	('879', 'Meltan', 'Acero', '7'),
	('880', 'Melmetal', 'Acero', '7'),
	('881', 'Grookey', 'Planta', '8'),
	('882', 'Thwackey', 'Planta', '8'),
	('883', 'Rillaboom', 'Planta', '8'),
	('884', 'Scorbunny', 'Fuego', '8'),
	('885', 'Raboot', 'Fuego', '8'),
	('886', 'Cinderace', 'Fuego', '8'),
	('887', 'Sobble', 'Agua', '8'),
	('888', 'Drizzile', 'Agua', '8'),
	('889', 'Inteleon', 'Agua', '8'),
	('890', 'Skwovet', 'Normal', '8'),
	('891', 'Greedent', 'Normal', '8'),
	('892', 'Rookidee', 'Volador', '8'),
	('893', 'Corvisquire', 'Volador', '8'),
	('894', 'Corviknight', 'Volador,Acero', '8'),
	('895', 'BlipBicho', 'Bicho', '8'),
	('896', 'Dottler', 'Bicho,Psiquico', '8'),
	('897', 'Orbeetle', 'Bicho,Psiquico', '8'),
	('898', 'Nickit', 'Siniestro', '8'),
	('899', 'Thievul', 'Siniestro', '8'),
	('900', 'Gossifleur', 'Planta', '8'),
	('901', 'Eldegoss', 'Planta', '8'),
	('902', 'Woolooo', 'Normal', '8'),
	('903', 'Dubwool', 'Normal', '8'),
	('904', 'Chewtle', 'Agua', '8'),
	('905', 'Drednaw', 'Agua,Roca', '8'),
	('906', 'Yamper', 'Electrico', '8'),
	('907', 'Boltund', 'Electrico', '8'),
	('908', 'Rolycoly', 'Roca', '8'),
	('909', 'Carkol', 'Roca,Fuego', '8'),
	('910', 'Coalossal', 'Roca,Fuego', '8'),
	('911', 'Applin', 'Planta,Dragon', '8'),
	('912', 'Flapple', 'Planta,Dragon', '8'),
	('913', 'Appletun', 'Planta,Dragon', '8'),
	('914', 'Silicobra', 'Tierra', '8'),
	('915', 'Sandaconda', 'Tierra', '8'),
	('916', 'Cramorant', 'Volador,Agua', '8'),
	('917', 'Arrokuda', 'Agua', '8'),
	('918', 'Barraskewda', 'Agua', '8'),
	('919', 'Toxel', 'Electrico,Veneno', '8'),
	('920', 'Toxtricity', 'Electrico,Veneno', '8'),
	('921', 'Sizzlipede', 'Fuego,Bicho', '8'),
	('922', 'Centiskorch', 'Fuego,Bicho', '8'),
	('923', 'Clobbopus', 'Lucha', '8'),
	('924', 'Grapploct', 'Lucha', '8'),
	('925', 'Sinistea', 'Fantasma', '8'),
	('926', 'Polteageist', 'Fantasma', '8'),
	('927', 'Hatenna', 'Psiquico', '8'),
	('928', 'Hattrem', 'Psiquico', '8'),
	('929', 'Hatterene', 'Psiquico,Hada', '8'),
	('930', 'Impidimp', 'Siniestro,Hada', '8'),
	('931', 'Morgrem', 'Siniestro,Hada', '8'),
	('932', 'Grimmsnarl', 'Siniestro,Hada', '8'),
	('933', 'Obstagoon', 'Siniestro,Normal', '8'),
	('934', 'Perrserker', 'Acero', '8'),
	('935', 'Cursola', 'Fantasma', '8'),
	('936', 'Sirfetch\'d', 'Lucha', '8'),
	('937', 'Mr. Rime', 'Hielo,Psiquico', '8'),
	('938', 'Runerigus', 'Tierra,Fantasma', '8'),
	('939', 'Milcery', 'Hada', '8'),
	('940', 'Alcreamie', 'Hada', '8'),
	('941', 'Falinks', 'Lucha', '8'),
	('942', 'Pincurchin', 'Electrico', '8'),
	('943', 'Snom', 'Hielo,Bicho', '8'),
	('944', 'Frosmoth', 'Hielo,Bicho', '8'),
	('945', 'Stonjourner', 'Roca', '8'),
	('946', 'Eiscue', 'Hielo', '8'),
	('947', 'Indeedee', 'Psiquico,Normal', '8'),
	('948', 'Morpeko', 'Electrico,Siniestro', '8'),
	('949', 'Cufant', 'Acero', '8'),
	('950', 'Copperajah', 'Acero', '8'),
	('951', 'Dracozolt', 'Electrico,Dragon', '8'),
	('952', 'Arctozolt', 'Electrico,Hielo', '8'),
	('953', 'Dracovish', 'Agua,Dragon', '8'),
	('954', 'Arctovish', 'Agua,Hielo', '8'),
	('955', 'Duralodon', 'Acero,Dragon', '8'),
	('956', 'Dreepy', 'Dragon,Fantasma', '8'),
	('957', 'Drakloak', 'Dragon,Fantasma', '8'),
	('958', 'Dragapult', 'Dragon,Fantasma', '8'),
	('959', 'Zacian', 'Hada', '8'),
	('960', 'Zacian Crowned', 'Hada,Acero', '8'),
	('961', 'Zamazenta', 'Lucha', '8'),
	('962', 'Zamazenta Crowned', 'Lucha,Acero', '8'),
	('963', 'Eternatus', 'Veneno,Dragon', '8'),
	('964', 'Kubfu', 'Lucha', '8'),
	('965', 'Urshifu Single Strike', 'Lucha,Siniestro', '8'),
	('966', 'Urshifu Rapide Strike', 'Lucha,Agua', '8'),
	('967', 'Zarude', 'Siniestro,Planta', '8'),
	('968', 'Regileki', 'Electrico', '8'),
	('969', 'Regidrago', 'Dragon', '8'),
	('970', 'Glastrier', 'Hielo', '8'),
	('971', 'Spectrier', 'Fantasma', '8'),
	('972', 'Calyrex', 'Psiquico,Planta', '8'),
	('973', 'Calyrex Hielo Rider', 'Psiquico,Hielo', '8'),
	('974', 'Calyrex Shadow Rider', 'Psiquico,Fantasma', '8'),
	('975', 'Wydeer', 'Normal,Psiquico', '8'),
	('976', 'Kleavor', 'Bicho,Roca', '8'),
	('977', 'Ursaluna', 'Tierra,Normal', '8'),
	('978', 'Basculegion', 'Agua,Fantasma', '8'),
	('979', 'Sneasler', 'Lucha,Veneno', '8'),
	('980', 'Overqwil', 'Siniestro,Veneno', '8'),
	('981', 'Enamorus', 'Hada,Volador', '8'),
	('982', 'Sprigatito', 'Planta', '9'),
	('983', 'Floragato', 'Planta', '9'),
	('984', 'Meowscarada', 'Planta,Siniestro', '9'),
	('985', 'Fuecoco', 'Fuego', '9'),
	('986', 'Crocalor', 'Fuego', '9'),
	('987', 'Skeledirge', 'Fuego,Fantasma', '9'),
	('988', 'Quaxly', 'Agua', '9'),
	('989', 'Quaxwell', 'Agua', '9'),
	('990', 'Quaquaval', 'Agua,Lucha', '9'),
	('991', 'Lechonk', 'Normal', '9'),
	('992', 'Oinkologne', 'Normal', '9'),
	('993', 'Tarountula', 'Bicho', '9'),
	('994', 'Spidops', 'Bicho', '9'),
	('995', 'Nymble', 'Bicho', '9'),
	('996', 'Lokix', 'Bicho,Siniestro', '9'),
	('997', 'Pawmi', 'Electrico', '9'),
	('998', 'Pawmo', 'Electrico,Lucha', '9'),
	('999', 'Pawmot', 'Electrico,Lucha', '9'),
	('1000', 'Tandemaus', 'Normal', '9'),
	('1001', 'Maushold', 'Normal', '9'),
	('1002', 'Fidough', 'Hada', '9'),
	('1003', 'Dachsbun', 'Hada', '9'),
	('1004', 'Smoliv', 'Planta,Normal', '9'),
	('1005', 'Dolliv', 'Planta,Normal', '9'),
	('1006', 'Arboliva', 'Planta,Normal', '9'),
	('1007', 'Squawkabilly', 'Normal,Volador', '9'),
	('1008', 'Nacli', 'Roca', '9'),
	('1009', 'Naclstack', 'Roca', '9'),
	('1010', 'Garganacl', 'Roca', '9'),
	('1011', 'Charcadet', 'Fuego', '9'),
	('1012', 'Armarouge', 'Fuego,Psiquico', '9'),
	('1013', 'Ceruledge', 'Fuego,Fantasma', '9'),
	('1014', 'Tadbulb', 'Electrico', '9'),
	('1015', 'Bellibolt', 'Electrico', '9'),
	('1016', 'Wattrel', 'Electrico,Volador', '9'),
	('1017', 'Kilowattrel', 'Electrico,Volador', '9'),
	('1018', 'Maschiff', 'Siniestro', '9'),
	('1019', 'Mabosstiff', 'Siniestro', '9'),
	('1020', 'Shroodle', 'Veneno,Normal', '9'),
	('1021', 'Grafaiai', 'Veneno,Normal', '9'),
	('1022', 'Bramblin', 'Planta,Fantasma', '9'),
	('1023', 'Brambleghast', 'Planta,Fantasma', '9'),
	('1024', 'Toedscool', 'Tierra,Planta', '9'),
	('1025', 'Toedscruel', 'Tierra,Planta', '9'),
	('1026', 'Klawf', 'Roca', '9'),
	('1027', 'Capsakid', 'Planta', '9'),
	('1028', 'Scovillain', 'Planta,Fuego', '9'),
	('1029', 'Rellor', 'Bicho', '9'),
	('1030', 'Rabsca', 'Bicho,Psiquico', '9'),
	('1031', 'Flittle', 'Psiquico', '9'),
	('1032', 'Espathra', 'Psiquico', '9'),
	('1033', 'Tinkatink', 'Hada,Acero', '9'),
	('1034', 'Tinkatuff', 'Hada,Acero', '9'),
	('1035', 'Tinkaton', 'Hada,Acero', '9'),
	('1036', 'Wiglett', 'Agua', '9'),
	('1037', 'Wugtrio', 'Agua', '9'),
	('1038', 'Bombirdier', 'Volador,Siniestro', '9'),
	('1039', 'Finizen', 'Agua', '9'),
	('1040', 'Palafin', 'Agua', '9'),
	('1041', 'Varoom', 'Acero,Veneno', '9'),
	('1042', 'Revavroom', 'Acero,Veneno', '9'),
	('1043', 'Cyclizar', 'Dragon,Normal', '9'),
	('1044', 'Orthworm', 'Acero', '9'),
	('1045', 'Glimmet', 'Roca,Veneno', '9'),
	('1046', 'Glimmora', 'Roca,Veneno', '9'),
	('1047', 'Greavard', 'Fantasma', '9'),
	('1048', 'Houndstone', 'Fantasma', '9'),
	('1049', 'Flamigo', 'Volador,Lucha', '9'),
	('1050', 'Cetoddle', 'Hielo', '9'),
	('1051', 'Cetitan', 'Hielo', '9'),
	('1052', 'Veluza', 'Agua,Psiquico', '9'),
	('1053', 'Dondozo', 'Agua', '9'),
	('1054', 'Tatsugiri', 'Dragon,Agua', '9'),
	('1055', 'Annihilape', 'Lucha,Fantasma', '9'),
	('1056', 'Clodsire', 'Veneno,Tierra', '9'),
	('1057', 'Farigiraf', 'Normal,Psiquico', '9'),
	('1058', 'Dudunsparce', 'Normal', '9'),
	('1059', 'Kingambit', 'Siniestro,Acero', '9'),
	('1060', 'Great Tusk', 'Tierra,Lucha', '9'),
	('1061', 'Scream Tail', 'Hada,Psiquico', '9'),
	('1062', 'Brune Bonnet', 'Planta,Siniestro', '9'),
	('1063', 'Flutter Mane', 'Fantasma,Hada', '9'),
	('1064', 'Slither Wing', 'Bicho,Lucha', '9'),
	('1065', 'Sandy Shocks', 'Electrico,Tierra', '9'),
	('1066', 'Iron Treads', 'Tierra,Acero', '9'),
	('1067', 'Iron Bundle', 'Hielo,Agua', '9'),
	('1068', 'Iron Hands', 'Lucha,Electrico', '9'),
	('1069', 'Iron Jugulis', 'Siniestro,Volador', '9'),
	('1070', 'Iron Moth', 'Fuego,Veneno', '9'),
	('1071', 'Iron Thorns', 'Roca,Electrico', '9'),
	('1072', 'Frigibax', 'Dragon,Hielo', '9'),
	('1073', 'Arctibax', 'Dragon,Hielo', '9'),
	('1074', 'Baxcalibur', 'Dragon,Hielo', '9'),
	('1075', 'Gimmighoul', 'Fantasma', '9'),
	('1076', 'Gholdengo', 'Acero,Fantasma', '9'),
	('1077', 'Wo-Chien', 'Siniestro,Planta', '9'),
	('1078', 'Chien-Pao', 'Siniestro,Hielo', '9'),
	('1079', 'Ting-Lu', 'Siniestro,Tierra', '9'),
	('1080', 'Chi-Yu', 'Siniestro,Fuego', '9'),
	('1081', 'Roaring Moon', 'Dragon,Siniestro', '9'),
	('1082', 'Iron Valiant', 'Hada,Lucha', '9'),
	('1083', 'Koraidon', 'Lucha,Dragon', '9'),
	('1084', 'Miraidon', 'Electrico,Dragon', '9'),
	('1085', 'Walking Wake', 'Agua,Dragon', '9'),
	('1086', 'Iron Leaves', 'Planta,Psiquico', '9'),
	('1087', 'Dipplin', 'Planta,Dragon', '9'),
	('1088', 'Poltchageist', 'Planta,Fantasma', '9'),
	('1089', 'Sinistcha', 'Planta,Fantasma', '9'),
	('1090', 'Okidogi', 'Veneno,Lucha', '9'),
	('1091', 'Minkidori', 'Veneno,Psiquico', '9'),
	('1092', 'Fezandipiti', 'Veneno,Hada', '9'),
	('1093', 'Ogerpon Teal Mask', 'Planta', '9'),
	('1094', 'Ogerpon Wellspring Mask', 'Planta,Agua', '9'),
	('1095', 'Ogerpon Hearthflame Mask', 'Planta,Fuego', '9'),
	('1096', 'Ogerpon Cornerstone Mask', 'Roca,Agua', '9'),
	('1097', 'Archaludon', 'Acero,Dragon', '9'),
	('1098', 'Hydrapple', 'Planta,Dragon', '9'),
	('1099', 'Gouginf Fuego', 'Fuego,Dragon', '9'),
	('1100', 'Raging Bolt', 'Electrico,Dragon', '9'),
	('1101', 'Iron Boulder', 'Roca,Psiquico', '9'),
	('1102', 'Iron Crown', 'Acero,Psiquico', '9'),
	('1103', 'Terapagos', 'Normal', '9'),
	('1104', 'Percharunt', 'Veneno,Fantasma', '9');

-- Estructura tabla Equipos
CREATE TABLE IF NOT EXISTS Equipos (
    Equipo	INT NOT NULL PRIMARY KEY,
    Pokemon1	INT NOT NULL,
    Pokemon2	INT NOT NULL,
    Pokemon3	INT NOT NULL,
    Pokemon4	INT NOT NULL,
    Pokemon5	INT NOT NULL,
    Pokemon6	INT NOT NULL,
    FOREIGN KEY (Pokemon1) REFERENCES Pokemon(idPokemon) ON DELETE CASCADE,
    FOREIGN KEY (Pokemon2) REFERENCES Pokemon(idPokemon) ON DELETE CASCADE,
    FOREIGN KEY (Pokemon3) REFERENCES Pokemon(idPokemon) ON DELETE CASCADE,
    FOREIGN KEY (Pokemon4) REFERENCES Pokemon(idPokemon) ON DELETE CASCADE,
    FOREIGN KEY (Pokemon5) REFERENCES Pokemon(idPokemon) ON DELETE CASCADE,
    FOREIGN KEY (Pokemon6) REFERENCES Pokemon(idPokemon) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Volcado de datos para la tabla Equipos
INSERT INTO Equipos (Equipo, Pokemon1, Pokemon2, Pokemon3, Pokemon4, Pokemon5, Pokemon6) VALUES
	('1', '987', '999', '996', '1010', '1035', '912'),
	('2', '192', '447', '976', '978', '506', '532'),
	('3', '889', '805', '894', '910', '929', '958'),
	('4', '654', '196', '847', '166', '773', '1083'),
	('5', '802', '770', '263', '941', '1021', '218'),
	('6', '1006', '468', '559', '1066', '816', '843');
